/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_18131273_proyecto_04;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose angel
 */
public class PA_18131273_Frame_04 extends javax.swing.JFrame {

    /**
     * Creates new form PA_18131273_Frame_04
     */
    Circulo []objetos;//Arreglo de circulos
    DefaultTableModel modelo;//modelo de la tabla
    public PA_18131273_Frame_04() {
        initComponents();
        this.setLocationRelativeTo(null);//Abrir la venta en el centro de la pantalla
        modelo = (DefaultTableModel)jTableDatos.getModel();//obtenemos el modelo de la tabla
        jTableDatos.setShowGrid(true);//Activamos la cuadricula de la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jButDefinirTamanio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextCantidad = new javax.swing.JTextField();
        jButGrabar = new javax.swing.JButton();
        JpanelDibujo = new java.awt.Panel();
        jButMostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButAleatorios = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenuAbrir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PA_18131273_Proyecto_04");
        setIconImage(getIconImage());
        setResizable(false);

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Color", "Tamaño", "Coordenada x", "Coordenada y"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDatos);

        jButDefinirTamanio.setText("Definir tamaño");
        jButDefinirTamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDefinirTamanioActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad de circulos:");

        jTextCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButGrabar.setText("Grabar datos");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelDibujoLayout = new javax.swing.GroupLayout(JpanelDibujo);
        JpanelDibujo.setLayout(JpanelDibujoLayout);
        JpanelDibujoLayout.setHorizontalGroup(
            JpanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        JpanelDibujoLayout.setVerticalGroup(
            JpanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        jButMostrar.setText("Mostrar");
        jButMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMostrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Colores disponibles");

        jLabel3.setText("1");

        jLabel4.setText("2");

        jLabel5.setText("3");

        jLabel6.setText("4");

        jLabel7.setText("5");

        jLabel8.setText("6");

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(0, 0, 255));
        jLabel10.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(0, 255, 0));
        jLabel11.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(255, 255, 0));
        jLabel12.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(255, 0, 255));
        jLabel13.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(153, 153, 153));
        jLabel14.setOpaque(true);

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131273_proyecto_04/Asignacion.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131273_proyecto_04/Descripcion.png"))); // NOI18N

        jMenu1.setText("Archivo");

        jMenuNuevo.setText("Nuevo");
        jMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNuevo);

        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuGuardar);

        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbrir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButDefinirTamanio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButAleatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel16))
                            .addComponent(JpanelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButDefinirTamanio)
                            .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButGrabar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButMostrar)
                            .addComponent(jButAleatorios))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpanelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel16)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

@Override//Icono de la aplicacion
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("pa_18131273_proyecto_04/icono.png"));
        return retValue;
    }
    private void jButDefinirTamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDefinirTamanioActionPerformed
        modelo.setRowCount(Integer.parseInt(jTextCantidad.getText()));//Establecemos la cantidad de renglones deseados desde la etiqueta cantidad    
        objetos = new Circulo[Integer.parseInt(jTextCantidad.getText())];//Establecemos el tamaño del arreglo en base a la etiqueta cantidad
        for (int i = 0; i < objetos.length; i++) {
            objetos[i] = new Circulo();//Inicializamos los objetos con valores por defecto
            objetos[i].setIdentificador(Romano.getNumeroEquivalente((i+1)));//le damos al objeto el identificador con su equivalente en romano  sumamos +1 ya que en romano no existe el 0
            modelo.setValueAt(objetos[i].getIdentificador(), i, 0);//Escribimos el valor en la tabla 
        }
        jButDefinirTamanio.setEnabled(false);//Desactivamos el boton una vez que se ha establecido la dimension
     
    }//GEN-LAST:event_jButDefinirTamanioActionPerformed

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        for (int i = 0; i < objetos.length; i++) {//grabamos los valores al objeto extrayendolos de la tabla
            objetos[i].setColor(Integer.parseInt(modelo.getValueAt(i, 1)+""));//Color
            objetos[i].setTamanio(Integer.parseInt(modelo.getValueAt(i, 2)+""));//Tamaño
            objetos[i].setX(Integer.parseInt(modelo.getValueAt(i, 3)+""));//Coordenada x
            objetos[i].setY(Integer.parseInt(modelo.getValueAt(i, 4)+""));//Coordenada y
        }
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jButMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMostrarActionPerformed
        for (int i = 0; i < objetos.length; i++) {
            objetos[i].dibujar(JpanelDibujo);//Dibujamos los circulos con todos sus datos establecidos
        }
    }//GEN-LAST:event_jButMostrarActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        Random azar = new Random();//Objeto para valores aleatorios
        for (int i = 0; i < objetos.length; i++) {
            modelo.setValueAt(1+azar.nextInt(6), i, 1);//Valor aleatorio para el color
            modelo.setValueAt(10+azar.nextInt(120), i, 2);//Valor aleatorio para el tamaño (+10 para evitar tamaños pequeños o iguales a 0)
            modelo.setValueAt(+azar.nextInt(780), i, 3);//Valor para coordenada x
            modelo.setValueAt(+azar.nextInt(150), i, 4);//Valor para coordenada y
        }
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
        JFileChooser jfch = new JFileChooser();//Objeto file chooser
        
        if(jfch.showSaveDialog(jLabel1) != 0 || modelo.getRowCount() == 0){//Comprobamos si hay renglones en la tabla
             JOptionPane.showMessageDialog(rootPane, "No hay datos para guardar");//Si no es asi, le damos a conocer al usario que no ha ingresado datos
            return;
        }
        
        FileWriter fw = null;
        PrintWriter pw = null;
    
        //El orden de escritura sera
        //Tamaño del arreglo
        //Identificador del circulo
        //Color del circulo
        //Tamaño del circulo
        //Coordenada x del circulo
        //Coordenada y del circulo
        try {//Abrimos el flujo de archivos
            fw = new FileWriter(jfch.getSelectedFile());
            pw = new PrintWriter(fw);
            
            pw.println(objetos.length);//Escribimos la dimension en el archivo
            
            for (int i = 0; i < objetos.length; i++) {
                pw.println(objetos[i].getIdentificador());//Escribimos el identificador en el archivo
                pw.println(objetos[i].getColor());//Escribimos el color en el archivo
                pw.println(objetos[i].getTamanio());//Escribimos el tamaño en el archivo
                pw.println(objetos[i].getX());//Escribimos la coordenada x en el archivo
                pw.println(objetos[i].getY());//Escribimos la coordenada y en el archivo
                
            }
            //Cerramos el flujo de archivos
            pw.close();
            fw.close();
           //Se evitan las excepciones
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PA_18131273_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PA_18131273_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        } 
        

  
        
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
     //Eliminamos datos que esten escritos antes de cargar los guardados
     jMenuNuevo.doClick();
        JFileChooser jfch = new JFileChooser();
         
         if(jfch.showOpenDialog(jLabel1) != 0)
             return;
         
         FileReader fr = null;
         BufferedReader br = null;
         
        
        try {//Abrimos el flujo de archivos
            fr = new FileReader(jfch.getSelectedFile());
            br = new BufferedReader(fr);
           
            int cantidad = Integer.parseInt(br.readLine());//obtenemos la cantidad del archivo
            jTextCantidad.setText(cantidad+"");//Actualizamos la etiqueta
            jButDefinirTamanio.doClick();//Llamamos al evento del boton definir
            
            for (int r = 0; r < objetos.length; r++) 
                for (int c = 0; c < modelo.getColumnCount(); c++) {
                    modelo.setValueAt(br.readLine(), r, c);//obtenemos los valores y los escribimos en la tabla
                }
             jButGrabar.doClick();//Llamamos al evento del boton grabar para evitar una excepcion por parte del usuario
              jButMostrar.doClick();//Mostramos los dibujos guardados
            //Cerrramos el flujo de archivos          
            br.close();
            fr.close();
          
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PA_18131273_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PA_18131273_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        }     
                
        
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    private void jMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevoActionPerformed
        jTextCantidad.setText("");//borramos el valor de la cantidad
        jButDefinirTamanio.setEnabled(true);//Reactivamos el boton definir tamaño
        
        modelo.setRowCount(0);//Quitamos los renglones a la tabla
        
        JpanelDibujo.repaint();//Eliminamos los dibujos 
        
    }//GEN-LAST:event_jMenuNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_18131273_Frame_04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel JpanelDibujo;
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButDefinirTamanio;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JTextField jTextCantidad;
    // End of variables declaration//GEN-END:variables
}
